version: '3'
services:
  app:
    build: ./
    restart: always
    env_file:
      - .env.local
    ports:
      - "5000:80"
    volumes:
      - /tmp:/tmp
  
  nginx:
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"